/// Flutter icons SmartTurklistan
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SmartTurklistan
///      fonts:
///       - asset: fonts/SmartTurklistan.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SmartTurklistan {
  SmartTurklistan._();

  static const _kFontFam = 'SmartTurklistan';
  static const _kFontPkg = null;

  static const IconData tenge = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_bag = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData police = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData photo_camera = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData opros = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData monitoring_tsen = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ddd = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData voice_command = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData taxi_sign = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
