name: cat_box
description: View cats that are up for adoption.

# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Bold.ttf
        - asset: fonts/Ubuntu-Regular.ttf

  assets:
    - assets/cats.json
    - images/profile_header_background.png